### ISSUE TITLE
Increase the choice of variables sorter

### ISSUE THREAD

**Issue by fbigun** [chrisallenlane/cheat#187]
Proposed to replace the output sorter view less

Command interpreter is too long, do not see the head of the information.

**Comment by chrisallenlane** [comment]
In order to assert that `cheat` continues to play nicely with other tools (I personally use `cheat` with `grep` all the time, for example), I don't think I want to make it invoke `less` by default. I think @chid has a good suggestion there, though, whereby you could simply alias the `cheat` command to your liking.
