### ISSUE TITLE
Caching for name=>file-path mapping?

### ISSUE THREAD

**Issue by idf** [chrisallenlane/cheat#214]
From function `def get()` in the [file](https://github.com/chrisallenlane/cheat/blob/master/cheat/sheets.py), is there a caching mechanism for `cheats = {}`? It seems that every time invoking `$ cheat <cheatsheet>`, the file system is re-traversed and the mapping is re-constructed, which hinders further scaling.

**Comment by chrisallenlane** [comment]
You're right that this is not as efficient as it could be. Initially, I actually was caching the results of the filesystem scan, but eventually had to roll that back:

https://github.com/chrisallenlane/cheat/commit/718ec4f6856a7c1a7f1ddb3dbccdba569b424c29

I don't remember entirely why caching the file system read was a bad idea, but it turned out to be a bad idea. If I remember correctly, it had something to do with this:

https://github.com/chrisallenlane/cheat/issues/180

I think there was an edge-case that would occur when attempting to edit a newly-created cheatsheet or something. (I don't have the time right now to dig through all of the tickets to remind myself precisely what the problem was, but I'm very confident that this caching approach did cause problems :smile:)

With that said, I'm happy to leave good-enough alone here, given that `cheat` is not a performance-dependent application to any meaningful extent anyway.

Thanks for the issue, regardless :+1:

**Comment by idf** [comment]
:+1:
