### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by pr0letariat** [chrisallenlane/cheat#237]
I run the following command with the following output:

    $ pip install --upgrade cheat
    Downloading/unpacking cheat
    Downloading cheat-2.1.15.tar.gz
    Running setup.py (path:/tmp/pip-build-z3jNTK/cheat/setup.py) egg_info for package cheat
    
    Downloading/unpacking docopt>=0.6.1 (from cheat)
    Downloading docopt-0.6.2.tar.gz
    Running setup.py (path:/tmp/pip-build-z3jNTK/docopt/setup.py) egg_info for package docopt
    
    Downloading/unpacking pygments>=1.6.0 (from cheat)
    Downloading Pygments-2.0.2-py2-none-any.whl (672kB): 672kB downloaded
    Installing collected packages: cheat, docopt, pygments
    Running setup.py install for cheat
    changing mode of build/scripts-2.7/cheat from 664 to 775
    
    changing mode of /home/me/.local/bin/cheat to 775
    Running setup.py install for docopt
    
    Successfully installed cheat docopt pygments
    Cleaning up...`

But when I do:

    $ cheat -v
    cheat 2.1.13

It still says the older version?

**Comment by chrisallenlane** [comment]
I'm honestly not particularly fluent in python or its build tools, unfortunately. Perhaps you can try the "unplug it, then plug it back in" approach?

```sh
sudo pip uninstall cheat
sudo pip install cheat
```

This should be safe, because your personal cheatsheets are not saved among the pip files, so you won't lose them if you uninstall and re-install.

Also: did you install it using `sudo` the first time? If you did, perhaps the problem is that you're not using it now?

Hopefully someone more knowledgeable than me can chime in here.
