### ISSUE TITLE
Permissive license discussion

### ISSUE THREAD

**Issue by igorshubovych** [chrisallenlane/cheat#261]
Hello,

That was a discussion in [tldr project](https://github.com/tldr-pages/tldr) about possibility to collaborate with cheat:
- https://github.com/tldr-pages/tldr/issues/266#issuecomment-168738924

I see 3 possibilities:
- Double licensing with GPL and MIT
- Decoupling pages into separate repo and license them separately as MIT, Creative Commons or any other permissive license
- Relicensing, which might be hard as many people are already using cheat.

Any thoughts on that?

**Comment by dufferzafar** [comment]
I would personally favor the 2nd way, because I currently use my own implementation of cheat (in Go), but the cheatsheets are fetched from this repo.

Having the sheets separate from the actual tool will simplify things for people like me. :smile_cat:

**Comment by chrisallenlane** [comment]
@igorshubovych 

Thanks for following up on this discussion.

Let's treat these items as separate concerns:

1. Licensing
2. Externalizing cheatsheets for use with other programs

I agree that both do need to be addressed.

Regarding licensing:

I did some research on this, and I've made the "executive decision" to go with your "option 1" here. As of `cheat` version `2.1.22`, `cheat` is now dual-licensed under both the GPL3 and MIT licenses.

If either you (@igorshubovych) or anyone else has a concern with that approach, please say so. However, as best as I could tell from my own research, this approach has no downsides, and maximizes liberty (which is the goal, in my mind).

Regarding externalizing cheatsheets:

I believe that externalizing the cheatsheets could have some value, provided that we first thoroughly think through the implications that that change could have. I'm going to think about this for a little bit, and I'll then open a new ticket dedicated solely to this issue once I've had time to gather my thoughts. When I open that new ticket, I'll tag committers from the appropriate related projects so we can have a discussion.

Please let me know what you think about all of the above.

I'm going to close this ticket as resolved for now, but please feel free to re-open it if you feel that's necessary.

Thanks!

**Comment by igorshubovych** [comment]
Oh, that's great news! Thanks!

**Comment by lucaswerkmeister** [comment]
I have a concern: Do you have the permission to dual-license the program? You’re not the only person to have worked on it, and it’s unclear if the other contributors gave you permission to publish their contribution under a different license. As far as I can tell, there’s no text to the effect of “you agree to license your contribution under the GPLv3, or any other license chosen by the Maintainer” or something like that, so I would think that the contributions are GPLv3 only. GPLv3 does not allow anyone to take the code and distribute it under a non-copyleft license.

**Comment by chrisallenlane** [comment]
@lucaswerkmeister 

Thanks for raising that concern. To be honest, I hadn't even thought about that, given that 1) we were not revoking the original license, and 2) we are dual-licensing with another "free" license. I agree that this is murky, though.

At this point, I think the best I can do is simply to maintain the dual-license. This is my reasoning:

1. I applied the dual-license yesterday, published as `cheat` version `2.1.22`. In that sense, what's done is done, so we might as well move forward.

2. Presuming it's even an option, I don't want to revert yesterday's change, given that `cheat` will be useful to more people if it is dual-licensed. Additionally, the benefits of the dual-license are concrete and immediate, while contributors' objections to the change are, at this point, only hypothetical.

3. I hope that, given that MIT is itself a "free" license, prior contributors won't have objections to its application. (Of course, I won't blame anybody that does, given that a reasonable discussion can be had regarding which license is "freer".)

The murkiness is regrettable here, though, and I wish that I had the foresight such as not to paint us into this corner. At this point, however, I think it's probably best to stay this course with the dual-licensed approach.

With that said, I'll do a few things going forward:

1. I'll add some text to `CONTRIBUTING.md` clarifying the licensing situation for contributors.

2. I was hoping to merge in some more pull-requests today. Before I do so, I'll notify each contributor of the licensing change, and will wait to merge until I receive their "OK".

3. Upon request, I'll revert commits from contributors with objections to the new licensing scheme.

4. This is somewhat tangential, but I may also create a twitter account for the project, which can serve as the official channel for announcements related to the project.

How does the above sound, @lucaswerkmeister?

**Comment by lucaswerkmeister** [comment]
Sounds good to me. As far as I understand (but I am not a lawyer, I am not your lawyer, yadda yadda), only contributors would have any basis to sue you over this. In other words, I don’t think it’s possible that some random person comes in and crucifies you over adding another license. And it’s probably a reasonable assumption that none of the contributors will object to the change *that* much (if at all).

(For the record, I personally approve of the change.)

**Comment by chrisallenlane** [comment]
Thanks for the input, @lucaswerkmeister. We'll call this the plan going forward :+1:

**Comment by eMBee** [comment]
i just discovered this and related projects, and i wanted to share my experience and what i have learned from other re-licensing efforts.

it is indeed correct that formally all contributors need to be asked for a change in the license, even if it is to add a new license. there is something about minimal contributions that could be ignored, but to be on the safe side it's better to just ask everyone.

cheat today has 125 contributors. it would take a message to each one of them to get them to approve. 

that number could be reduced further by only counting submissions before the MIT license was added, assuming that everyone who submitted after that implicitly approves with the change.

the main effort i suspect will be to keep track of who agreed, and hunt down those who don't respond, and finally, consider what to do with contributions where approval can not be received.

things you may run into: 

people getting annoyed for being bothered over a single commandline they contributed a few years ago.
people disagreeing with the license change and then making a fuss about it.

there is also the question whether a single commandline example is even copyrigtable. (if you submit an example, then remove it because you disagree with it, and later i submit the same example, do you own the copyright to that? or we both submitted the same example to different projects (yours to cheat, mine to tldr), so who owns the copyright?)

rosettacode.org  gave up changing the license because they decided it would be to much effort to get approval from everyone.

squeak on the other hand went through the painstaking process of hunting down every contributor to their project spanning multiple decades, and then actually removed/rewrote the parts for people they couldn't get a hold of.

both of these projects though are a lot bigger than cheat, just to give a perspective.

**Comment by eMBee** [comment]
for fun i looked at git blame and sorted contributions by date. i found 139 different authors (although some have people multiple email addresses) 
sorting by date, 78 of those didn't commit anything since feb 16th 2016.
assuming that everyone who committed after the change is ok, then those 78 would be the ones that should be asked for their approval.

this is the command i used:
    find -type f -exec git blame -e \{\} \; | sed -e 's/[^(]*(//' -e 's/).*//' | awk '{ print $1, $2 }' | sort | uniq > contributors-by-name
from there i processed it in vim.

**Comment by chrisallenlane** [comment]
@lucaswerkmeister , @eMBee 

Thanks again for your input here. Given the v3 rewrite, I believe we may have a unique opportunity to change the license now. Please feel free to share any input on #477, if you'd like.
