### ISSUE TITLE
Allow `cheat` to use `$VISUAL` alongside `$EDITOR`

### ISSUE THREAD

**Issue by nagromc** [chrisallenlane/cheat#294]
When running `cheat -e`, I came across the messages provided in [utils.py](https://github.com/chrisallenlane/cheat/blob/f000756f2c895e2b5ede61e4214b1c0421fa863e/cheat/utils.py#L34). Yet, I have the `$VISUAL` env variable set.

A [Google search](https://www.google.com/search?hl=fr&q=environment+variables+editor+visual) return [some](http://unix.stackexchange.com/a/4861) [interesting](https://wiki.archlinux.org/index.php/environment_variables#Examples) [results](https://help.ubuntu.com/community/EnvironmentVariables#Preferred_application_variables). FWIU, `$EDITOR` seems to be used as a very basic editor, whereas `$VISUAL` as a full-featured one.

Maybe allowing `cheat` to use `$EDITOR` as a fallback of `$VISUAL` would be a good idea.

**Comment by lucaswerkmeister** [comment]
I think the conventional fallback order is `TOOL_EDITOR`, `VISUAL`, `EDITOR`, where `TOOL_EDITOR` is a tool-specific variable like `GIT_EDITOR` or `SUDO_EDITOR`. Sometimes a config option is also available.

**Comment by chrisallenlane** [comment]
Thanks for the discussion, guys. I've implemented respect for `CHEAT_EDITOR` and `VISUAL` (in addition to `EDITOR`) with the following commit:

https://github.com/chrisallenlane/cheat/commit/6be87e2d42d75d1c9c739e92d179f9f6295c53f7

I'm going to close this ticket as resolved, because that code should be merged into `master` and deployed later today.

Thanks!
