### ISSUE TITLE
Speed up colored output by caching colored cheatsheet.

### ISSUE THREAD

**Issue by gan-lin** [chrisallenlane/cheat#300]
Our goal is to show a help tip immediately, but colored output is a little slow. On my computer, showing first colored cheatsheet after startup may take more than one second, and following cheatsheets will take around 0.7 second.

My test show that the slowest step is to import Pygments. So if we cache the colored cheatsheet at the first time, following showing can be faster.

However, to add cache we have to change the showing logic in main batch and influenced code may be kind of much. If it's acceptable, I think I will add it. Thanks for reading my advise. :)

**Comment by chrisallenlane** [comment]
Sorry it's taken me so long to get to this!

I'd rather not implement a caching layer, simply because that adds complexity to what is intended to be a simple system. I will respectfully close this ticket.

Question, though: perhaps there's an issue with your local system in play? I'm running very modest hardware, but syntax highlighting imposes no observable performance penalty at all for me. Is it possible that:

1. Odd Python configuration is causing your modules to load slowly?
2. You have a failing hard drive?

I'm just shooting from the hip here, but my hunch is that something like the above could be a factor.
