### ISSUE TITLE
CHEATCOLORS not working or I'm not understanding it's function

### ISSUE THREAD

**Issue by AmauryOrtega** [chrisallenlane/cheat#378]
I'm using `zsh` on `Raspbian 9.4 streatch` and I installed `cheat` using `sudo pip3 install cheat`. I added 
```
# Env Variables
## Cheat (Python 3.x)
export CHEAT_EDITOR=vim
export CHEATCOLORS=true
```
into my `.zshrc` file.
Is this the behavior `CHEATCOLORS` should have? or I did something wrong?
![image](https://user-images.githubusercontent.com/12105142/37557738-437a1506-29d7-11e8-9337-389e98fcd918.png)

**Comment by AmauryOrtega** [comment]
@chrisallenlane

**Comment by AmauryOrtega** [comment]
@sundar-raman Thanks! It's weird  that `'CHEATCOLORS' in os.environ` isn't working properly

**Comment by chrisallenlane** [comment]
@AmauryOrtega, sorry it's taken me so long to address this.

The highlighting output by `cheat bash` looks correct to me.

@sundar-raman was correct in that if `CHEATCOLORS` were set to **any** value (not just `true`) that colorization would be applied regardless. His PR addressing the issue was merged in today, however, and will ship with the next release of `cheat`, which will likely be published over the next few days.

I'll close this as resolved now, but ping me if you have any remaining questions. Thanks.

**Comment by AmauryOrtega** [comment]
@chrisallenlane Thanks for your response. No harsh feelings about how long it took you to respond. This is a very handy tool that I still use to this day. Thanks for you work

**Comment by chrisallenlane** [comment]
Thanks, @AmauryOrtega :smile:
