### ISSUE TITLE
Uninstall cheat

### ISSUE THREAD

**Issue by tqlloki** [chrisallenlane/cheat#392]
Hi,

Can you help me how to uninstall cheat?

Thanks!

Best regards,

**Comment by DerUser** [comment]
`pip uninstall cheat` should do the trick

if you had some custom cheats they are still in `~/.cheat/`. Maybe you want to delete them to?

**Comment by Gisson** [comment]
Can this issue be closed, since there is no progress here?

**Comment by pirat89** [comment]
@DerUser really don't think so. You usually don't want to touch user's data. I can imagine someone would like to uninstall the cheat (e.g. because something is pretty messed up or just because will want to install it in different way) and after next installation you will loose your personal cheat records. Or imagine, you are using cheat but another user will uninstall it and you will loos your data again. I don't think you want to remove this directory as well.

**Comment by DerUser** [comment]
I thought it is a good idea to mention this. When you want to uninstall some software it may mean you don't want to use it anymore. In this line of thought the cheats in `~/.cheat` may be no longer needed.

**Comment by Gisson** [comment]
@DerUser that is not always the case. Sometimes you just want to reinstall it. And even if that is the case, in the event of wanting that software again, your custom configurations will be gone. Take for example some existing software, Firefox doesn't delete its dot folder, same for kde and many others.

**Comment by DerUser** [comment]
Anyway, I think this can be closed...

**Comment by chrisallenlane** [comment]
Thanks, guys.
