### ISSUE TITLE
snap: cannot access home dir

### ISSUE THREAD

**Issue by chrisallenlane** [chrisallenlane/cheat#414]
@bernermic, here's something I stumbled onto while taking a look at #412.

I uninstalled `cheat` from my system globally using `pip`. I then installed the `cheat` snap thusly:

    sudo snap install cheat

When I then attempted to view a cheatsheet, I got an error:

```
chris@fourside:~$ sudo snap install cheat
cheat v2.3.1.build.4 from Michael (bernermic) installed
chris@fourside:~$ cheat tar
Traceback (most recent call last):
  File "/snap/cheat/42/bin/cheat", line 80, in <module>
    print(colorize(sheet.read(options['<cheatsheet>'])), end="")
  File "/snap/cheat/42/lib/python3.5/site-packages/cheat/sheet.py", line 72, in read
    if not exists(sheet):
  File "/snap/cheat/42/lib/python3.5/site-packages/cheat/sheet.py", line 51, in exists
    return sheet in sheets.get() and os.access(path(sheet), os.R_OK)
  File "/snap/cheat/42/lib/python3.5/site-packages/cheat/sheets.py", line 43, in get
    for cheat in os.listdir(cheat_dir)
PermissionError: [Errno 13] Permission denied: '/home/chris/src/dotfiles/cheat'
```

(On my system, `DEFAULT_CHEAT_DIR` is `/home/chris/src/dotfiles/cheat`.)

When I uninstalled and reinstalled the `cheat` snap in "classic" confinement, however, the problem was resolved:

```
chris@fourside:~$ sudo snap remove cheat
cheat removed
chris@fourside:~$ sudo snap install cheat --classic
cheat v2.3.1.build.4 from Michael (bernermic) installed
chris@fourside:~$ cheat tar
# To extract an uncompressed archive:
tar -xvf /path/to/foo.tar

# etc, etc, etc
```

Question: do you think we should modify the `snapcraft.yaml` file to specify that `cheat` must be installed in `classic` confinement? I'm also wondering if this is part of the solution regarding #412.

I'll disclaim that I'm relatively new to the snap ecosystem, so I may be barking up the wrong tree here.

**Comment by bernermic** [comment]
@chrisallenlane no - that's an easy (but not clean way ;)) to solve this issue. The idea of snaps is, that they run within a 'strictly' confined space. 
This means the cheat snap in strict confinement creates it's own confined 'home' dir, which lives here: ~/snap/cheat/current/ and libraries, binaries etc. live here: /snap/cheat/current/
It does not have access to the user's $HOME.
This however could be solved by connecting the home interface within the snap. BUT: this way the snap can only access 'non' hidden files / folders - like .bashrc or .config/ ...

Installing snaps in the --classic confinement means you skip this whole security layer and make the snap work like a regular binary on your system. Means it can then access the users $HOME directory, hidden files/folders, vi and vim binary and so on.
So - you are right that it solves thes issues.
For now we can use the classic confinement to resolve the errors with access to the users env settings, but in the end I would like to go back to strict confinement (as classic confinement will be dropped at some point in time) and work with the interface definition instead.

I will try this with classic in the evening and report back.

**Comment by chrisallenlane** [comment]
> For now we can use the classic confinement to resolve the errors with access to the users env settings, but in the end I would like to go back to strict confinement (as classic confinement will be dropped at some point in time) and work with the interface definition instead.

That works for me. I would also prefer to use `strict` confinement in the end as well.

Regarding the environment variables - do you know of an interface that allows a snap to read external environment variables? (I read through the interface definitions, but didn't see anything promising.)

If not - perhaps we could create some snap config options. For example, if the snap can't read `CHEAT_EDITOR` from the external environment, perhaps we could expose a config option like:

    snap set cheat cheat_editor=vim

Or something like that. What do you think about that approach?

**Comment by bernermic** [comment]
@chrisallenlane I changed the confinement to classic and tried to upload the snap version now into the beta channel of the snapstore, but it is not allowed.

Classic confined snaps need manual review of a Canonical member.
`bernermic(18:01:42):~/temp/cheat (master) $ snapcraft push --release=edge cheat_v2.3.1.build.5_amd64.snap
Pushing cheat_v2.3.1.build.5_amd64.snap
After pushing, an attempt will be made to release to 'edge'
Preparing to push '/home/bernermic/temp/cheat/cheat_v2.3.1.build.5_amd64.snap' to the store.
Pushing cheat_v2.3.1.build.5_amd64.snap [====================================================================================================================================================================] 100%
Processing...|                                                                                                                                                                                                     
Will need manual review...
The Store automatic review failed.
A human will soon review your snap, but if you can't wait please write in the snapcraft forum asking for the manual review explicitly.
If you need to disable confinement, please consider using devmode, but note that devmode revision will only be allowed to be released in edge and beta channels.
Please check the errors and some hints below:
  - (NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required.`

Also with this snap in my clean setup calling `cheat -v` is not returning, but stays as open process.
![selection_001-cbca](https://user-images.githubusercontent.com/1283680/51402466-d9adf980-1b4d-11e9-8607-aecdc9302e31.png)

Next I tried to build the snap without classic confinement and simply installed it via --classic switch. This only does resolve your dedicated issue regarding snap is not able to detect your cheat directory within /home.
The issue with the editor is not resolved thow by this - the snap cannot access my locally installed vim. 
See:
`multipass@snappy:~/snap/cheat$ sudo snap install ./cheat_v2.3.1.build.5_amd64.snap --dangerous --classic 
cheat v2.3.1.build.5 installed
multipass@snappy:~/snap/cheat$ cheat -e file
You must set a CHEAT_EDITOR, VISUAL, or EDITOR environment variable in order to create/edit a cheatsheet.
multipass@snappy:~/snap/cheat$ export EDITOR=vim
multipass@snappy:~/snap/cheat$ cheat -e file
Could not launch vim
multipass@snappy:~/snap/cheat$ sudo apt install vim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
vim is already the newest version (2:7.4.1689-3ubuntu1.2).`

So I will try to specify the home plug and build a fresh version with this. I'll give you feedback when this is done.

**Comment by chrisallenlane** [comment]
Thanks for the update, @bernermic. Just shout if I can be of assistance.

Also, note that I just merged #391 into `master` moments ago, which changes how `cheat` is packaged and installed. That shouldn't really matter for your purposes, but it will be worth pulling in changes on `master` regardless, just to be safe.

**Comment by bernermic** [comment]
@chrisallenlane the latest version `v2.3.1.build.4` comes now with a home plug. So this should be able to read files in your folder `/home/chris/src/dotfiles/cheat`.
Can you please verify if this works now for you?

Then - I pulled in the changes from #391, but with this cheat snap does stop to run at all. I try to see how this can be resolved (can be tested via `sudo snap refresh --beta cheat`).
Result looks for me like this:
```  File "/snap/cheat/51/bin/cheat", line 75, in <module>
    print(utils.colorize(sheet.read(options['<cheatsheet>'])), end="")
  File "/snap/cheat/51/lib/python2.7/site-packages/cheat/sheet.py", line 74, in read
    if not self.exists(sheet):
  File "/snap/cheat/51/lib/python2.7/site-packages/cheat/sheet.py", line 54, in exists
    return (sheet in self._sheets.get() and
  File "/snap/cheat/51/lib/python2.7/site-packages/cheat/sheets.py", line 54, in get
    for cheat in os.listdir(cheat_dir)
OSError: [Errno 2] No such file or directory: '/usr/share/cheat'
```

**Comment by chrisallenlane** [comment]
@bernermic 

Thanks for the info. I just re-installed `cheat` from the `beta` channel and I'm now encountering the same issue about `/usr/share/cheat` not existing.

It makes sense why the issue occurs, I guess. Since #391 the system-wide cheatsheets are now installed to `/usr/share/cheat` instead of the old location.

Question (as someone who is still learning how snaps work) - is it possible to create that `/usr/share/cheat` directory as part of the process of building the snap? I _think_ that's all we need to do to resolve this.

**Comment by chrisallenlane** [comment]
@bernermic, please take a look at #416.

I made a few small changes to the project. In brief, this PR makes `setup.py` aware of the value of the `CHEAT_PATH` envvar.

So, if you do this:

```sh
python setup.py install
```

Cheatsheets will continue to install to `/usr/share/cheat` by default.

However, if you do this:

```sh
export CHEAT_PATH=/opt/cheat
python setup.py install
```

Cheatsheets will install to `/opt/cheat`.

(I'm doing the above as `root`. Also note that I'm using `/opt/cheat` as an example here. You could use whichever path is encouraged by the snap format.)

Of note is that, if you install cheat with `CHEAT_PATH` set, we'll need to ensure that `CHEAT_PATH` remains set to that same value within the snap at all times.

Do you think that would solve your problem?

**Comment by pirat89** [comment]
Hi guys, I am not familiar with `snap` and I will be superbusy next two weeks completely because of [#Devonf](https://devconfcz2019.sched.com/) (one really big conference). From the point of packaging in way we are doing, we are not affected by this change in any way so we are ok with it. We will try to look at installation scripts better later, whether it would be improved. In case it works for you guys, I think it's good solution even when I would prefer more something like option for setup.py script in case it's possible, e.g. `--cheat-path` instead of envar.

**Comment by pirat89** [comment]
I see. Actually not. I just thought it is possible :-D I am not using setup.py scripts usually. Anyway, you can keep it as it is and someone maybe later will send PR how to do it in better way.

**Comment by TomasKorbar** [comment]
Hi guys,
I've looked onto this and another option came out from stackoverflow here https://stackoverflow.com/questions/677577/distutils-how-to-pass-a-user-defined-parameter-to-setup-py
honestly i don't know which way is better or cleaner.
I will certainly ask guys from python team tomorrow.

**Comment by chrisallenlane** [comment]
Thanks, guys.

@TomasKorbar, I came across the same StackOverflow thread, but satisficed with the envvar solution after finding the answers non-straightforward. (I'm really surprised this is difficult in Python.) I appreciate the link, though.

> I will certainly ask guys from python team tomorrow.

I appreciate it. I'm eager to hear what they have to say. If there's a relatively simple way to implement this, I'll update the PR. Otherwise, I'll probably call the envvar approach "good enough" for now so we can get a new build shipped sooner.

**Comment by TomasKorbar** [comment]
@chrisallenlane I spoke today to one member of python team and he said that using environmental variable is completely ok.

**Comment by chrisallenlane** [comment]
Closing this as resolved with the addition of the `home` plug in the snap distribution.
